// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl8o9JoOpmhmBX56irgztejfc1CMFD78g',
    appId: '1:882177455207:web:3b807841f710f4c26e90c2',
    messagingSenderId: '882177455207',
    projectId: 'sigetu-b10c0',
    authDomain: 'sigetu-b10c0.firebaseapp.com',
    storageBucket: 'sigetu-b10c0.firebasestorage.app',
    measurementId: 'G-HFMEZ3LHL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANwsO3RoQGihTuUpF77hbLpJbDVlYpQ40',
    appId: '1:882177455207:android:600e3c219b1640ee6e90c2',
    messagingSenderId: '882177455207',
    projectId: 'sigetu-b10c0',
    storageBucket: 'sigetu-b10c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMThubvY32HwulXCgdahLFzjYuuzglx_g',
    appId: '1:882177455207:ios:fc2cfb26a3e112eb6e90c2',
    messagingSenderId: '882177455207',
    projectId: 'sigetu-b10c0',
    storageBucket: 'sigetu-b10c0.firebasestorage.app',
    iosBundleId: 'com.example.sigetu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMThubvY32HwulXCgdahLFzjYuuzglx_g',
    appId: '1:882177455207:ios:fc2cfb26a3e112eb6e90c2',
    messagingSenderId: '882177455207',
    projectId: 'sigetu-b10c0',
    storageBucket: 'sigetu-b10c0.firebasestorage.app',
    iosBundleId: 'com.example.sigetu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl8o9JoOpmhmBX56irgztejfc1CMFD78g',
    appId: '1:882177455207:web:75655aaa38d50eaa6e90c2',
    messagingSenderId: '882177455207',
    projectId: 'sigetu-b10c0',
    authDomain: 'sigetu-b10c0.firebaseapp.com',
    storageBucket: 'sigetu-b10c0.firebasestorage.app',
    measurementId: 'G-YKCE6CT20J',
  );
}
